### ISSUE TITLE
Building cleanslate 

### ISSUE THREAD

**Issue by V3rB0se** [tbalden/android_kernel_msm_redfin#1]
HI, I've been trying to build it but userland_worker.c inside init complains about missing binaries. i just checked the binaries are there but it still complaining about missing binaries 

```
msm-google/init/userland_worker.c:112:10: fatal error: '../binaries/hosts_k_zip.i' file not found
#include HOSTS_K_ZIP_FILE 
msm-google/init/userland_worker.c:110:47: note: expanded from macro 'HOSTS_K_ZIP_FILE'
#define HOSTS_K_ZIP_FILE                      "../binaries/hosts_k_zip.i"
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
 ```

**Comment by tbalden** [comment]
Run this one: https://github.com/tbalden/android_kernel_msm_redfin/blob/cleanslate-t-gki/binaries/convert
It will generate the .i files that are compiled in

**Comment by V3rB0se** [comment]
Thanks it worked! now its complaining about missing media/cam_sensor.h. 
is it msm_cam_sensor.h?

```
cleanslate/drivers/input/misc/vd6281/vd6281_module.c:33:10: fatal error: 'media/cam_sensor.h' file not found
#include <media/cam_sensor.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[6]: *** [/home/mc/cleanslate/scripts/Makefile.build:354: drivers/input/misc/vd6281/vd6281_module.o] Error 1
make[5]: *** [/home/mc/cleanslate/scripts/Makefile.build:651: drivers/input/misc/vd6281] Error 2
make[4]: *** [/home/mc/cleanslate/scripts/Makefile.build:651: drivers/input/misc] Error 2
make[3]: *** [/home/mc/cleanslate/scripts/Makefile.build:651: drivers/input] Error 2
make[3]: *** Waiting for unfinished jobs....
```

**Comment by tbalden** [comment]
It's a modular kernel with a certain repository structure, as Google created it.
Read here how you can build modular kernel multi repo kernels: https://source.android.com/docs/setup/build/building-kernels

**Comment by V3rB0se** [comment]
I'm little confused here, since its the first kernel I'm trying to build with this certain repository structure. I've been following this guide and successfully build the boot and vendor image out of it but it couldn't boot.
